chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'
urlpatterns = [
    path('start-chat/<int:dest_pk>/', start_chat, name='chat-start'),
    path('view/', chat_home, name='chat-home'),
    path('view/<int:pk>/', chat_view, name='chat-view'),
    path('delete/<int:pk>/', chat_delete, name='chat-delete'),
]

findLessons/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$|^/$|^home/$', homepage, name='homepage'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change-password'),
    path('profile/', include('user_profile.urls')),
    path('reservation/', include('reservation.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from .views import *

app_name = 'reservation'

urlpatterns = [
    path('', get_reservation_home, name='reservation_home'),
    path('search/<str:subject>/<str:city>/', get_filtered_list, name='search'),
    path('availability/<int:teacher_id>/', get_calendar, name='availability-list'),
    path('availability/create/', AvailabilityCreateView.as_view(), name='availability-create'),
    path('availability/update/<int:pk>/', AvailabilityUpdateView.as_view(), name='availability-update'),
    path('availability/delete/<int:pk>/', AvailabilityDeleteView.as_view(), name='availability-delete'),
    path('lesson/<int:pk>/', LessonDetailView.as_view(), name='lesson-view'),
    path('lesson/create/<int:availability_id>/', LessonCreateView.as_view(), name='lesson-create'),
    path('lesson/update/<int:pk>/', LessonUpdateView.as_view(), name='lesson-update'),
    path('lesson/delete/<int:pk>/<str:action>/', delete_lesson, name='lesson-delete'),
    path('rating/<int:teacher_id>/', create_update_rating, name='rating-create-update'),
    path('rating/delete/<int:pk>/', RatingDeleteView.as_view(), name='rating-delete'),
]

user_profile/urls.py
from django.urls import path
from .views import *

app_name = 'user_profile'
urlpatterns = [
    path('', profile_home, name='profile'),
    path('view/<int:pk>/', view_profile, name='view-profile'),
    path('set/', ProfileUpdateView.as_view(), name='set-profile'),
    path('set/teacher/', TeacherUpdateView.as_view(), name='set-teacher'),
    path('notification/', get_notifications, name='view-notification'),
    path('notification/delete/<int:pk>/', delete_notification, name='delete-notification'),
    path('request/<int:pk>/', RequestDetailView.as_view(), name='request-detail'),
    path('request/create/', RequestCreateView.as_view(), name='request-create'),
    path('request/delete/<int:pk>/<str:action>/', delete_request, name='request-delete'),
]

reservation/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _
from django.db import models

from user_profile.models import Profile, Teacher


# TO DO check possible inheritance between classes

# Create your models here.

class Lesson(models.Model):
    student = models.ForeignKey(Profile, related_name='lessons', on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, related_name='lessons', on_delete=models.CASCADE)
    subject = models.CharField(max_length=15)
    date = models.DateTimeField()

    def __str__(self):
        return 'ID: ' + str(self.pk) + ' -> ' + self.subject + ' on ' + str(self.date)


class Availability(models.Model):
    teacher = models.ForeignKey(Teacher, related_name='availabilities', on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return 'ID: ' + str(self.pk) + ' -> ' + str(self.date.date()) + ' at ' + str(self.date.time())


class Rating(models.Model):
    student = models.ForeignKey(Profile, related_name='ratings', on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, related_name='ratings', on_delete=models.CASCADE)
    stars = models.IntegerField(validators=[
            MinValueValidator(0, message=_('Value must be greater than or equal to 0')),
            MaxValueValidator(5, message=_('Value must be less than or equal to 5'))])

    def __str__(self):
        return ('ID: ' + str(self.pk) + ' -> ' + str(self.student.first_name) + ' ' + str(self.student.last_name) +
                ' to ' + str(self.teacher.profile.first_name) + ' ' + str(self.teacher.profile.last_name) +
                ': ' + str(self.stars))

reservation/views.py
from datetime import datetime, time

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, HttpResponseForbidden
from django.utils.timezone import make_aware
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from braces.views import GroupRequiredMixin

from reservation.forms import *
from reservation.models import Availability, Lesson, Rating
from user_profile.models import Profile, Teacher, Notification


# Create your views here.

def get_reservation_home(request):
    ctx = {'title': 'Reservation', 'object_list': Teacher.objects.all()}

    return render(request, template_name='reservation/reservation_home.html', context=ctx)


def get_filtered_list(request, subject, city):
    context = {
        'subject': subject,
        'city': city,
        'title': 'Search teacher'
    }

    queryset = Teacher.objects.filter(subjects__icontains=subject, city__iexact=city).order_by('price', '-stars')

    if request.method == 'POST':

        form = ReservationForm(request.POST)

        if form.is_valid():
            second_order = {'price': '-stars', '-stars': 'price'}
            order = form.cleaned_data['order']

            if order == 'stars':
                order = '-' + order

            start_date = form.cleaned_data.get('start_date')
            end_date = form.cleaned_data.get('end_date')

            # it's necessary to use the range function otherwise the problem occurs when there is an availability
            # greater than end_date (> start_date) and another less than the start_date (<end_date).
            # In this example the teacher is selected, but it's an error. It could also happen with start_date>end_date

            if start_date and end_date:
                start_date = timezone.make_aware(datetime.combine(start_date, time(0, 0)))
                end_date = timezone.make_aware(datetime.combine(end_date, time(23, 59, 59)))
                queryset = queryset.filter(availabilities__date__range=[start_date, end_date])
            elif start_date:
                start_date = timezone.make_aware(datetime.combine(start_date, time(0, 0)))
                queryset = queryset.filter(availabilities__date__gte=start_date)
            elif end_date:
                end_date = timezone.make_aware(datetime.combine(end_date, time(23, 59, 59)))
                queryset = queryset.filter(availabilities__date__lte=end_date)

            queryset = queryset.order_by(order, second_order[order]).distinct()
    else:
        form = ReservationForm()

    context['teachers'] = queryset
    context['form'] = form

    return render(request, 'reservation/reservation_home.html', context)


def get_calendar(request, teacher_id):
    teacher = get_object_or_404(Teacher, pk=teacher_id)
    is_me = (teacher.profile == request.user.profile) if request.user.is_authenticated else False

    today = make_aware(datetime.now())
    today_midnight= datetime.combine(today, time.min)

    start_date = today_midnight - timedelta(days=today.weekday())  # Start of this week (Monday)
    end_date = start_date + timedelta(days=20)  # 3 weeks of days (3 weeks * 7 days - 1 day)

    # Filter availability for the calculated range
    filtered_availability = Availability.objects.filter(
        teacher=teacher,
        date__gte=start_date,
        date__lt=end_date
    ).order_by('date')

    # Create a dictionary to store events by date
    events_by_date = {}
    for availability in filtered_availability:
        date_str = availability.date.strftime('%Y-%m-%d')
        time_str = availability.date.strftime('%H:%M')
        if date_str not in events_by_date:
            events_by_date[date_str] = []
        events_by_date[date_str].append({
            'type': 'availability',
            'time': time_str,
            'id': availability.id,
            'is_future': availability.date >= today,
        })

    if is_me:
        # Filter lessons for the calculated range
        filtered_lessons = Lesson.objects.filter(
            teacher=teacher,
            date__gte=start_date,
            date__lt=end_date
        ).order_by('date')

        for lesson in filtered_lessons:
            date_str = lesson.date.strftime('%Y-%m-%d')
            time_str = lesson.date.strftime('%H:%M')
            if date_str not in events_by_date:
                events_by_date[date_str] = []
            events_by_date[date_str].append({
                'type': 'lesson',
                'time': time_str,
                'subject': lesson.subject,
                'id': lesson.id,
                'is_future': lesson.date >= today,
            })

    # Sort events within each date
    for date_str in events_by_date:
        events_by_date[date_str].sort(key=lambda x: x['time'])

    # Create a list to store weeks and days for the calendar
    calendar_weeks = []
    current_date = start_date
    current_week = []

    while current_date <= end_date:
        date_str = current_date.strftime('%Y-%m-%d')
        current_week.append({
            'date': current_date,
            'events': events_by_date.get(date_str, [])
        })
        if len(current_week) == 7:
            calendar_weeks.append(current_week)
            current_week = []
        current_date += timedelta(days=1)

    if current_week:  # Add any remaining days in the last week
        calendar_weeks.append(current_week)

    ctx = {
        'title': 'Show availabilities',
        'teacher_name': teacher.profile.first_name + ' ' + teacher.profile.last_name,
        'today': today_midnight,
        'calendar_weeks': calendar_weeks,
        'is_me': is_me,
        'teacher_profile_id': teacher.profile.pk
    }

    return render(request, 'reservation/calendar.html', context=ctx)


class AvailabilityCreateView(GroupRequiredMixin, CreateView):
    group_required = ['Teachers']
    model = Availability
    title = 'Set availability'
    template_name = 'reservation/entity_create_update.html'
    form_class = AvailabilityForm

    def get_success_url(self):
        profile = get_object_or_404(Profile, user=self.request.user)
        teacher = get_object_or_404(Teacher, profile=profile)
        return reverse_lazy('reservation:availability-list', kwargs={'teacher_id': teacher.pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        profile = get_object_or_404(Profile, user=self.request.user)
        teacher = get_object_or_404(Teacher, profile=profile)
        kwargs['teacher'] = teacher
        return kwargs

    def form_valid(self, form):
        profile = get_object_or_404(Profile, user=self.request.user)
        teacher = get_object_or_404(Teacher, profile=profile)
        form.instance.teacher = teacher
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['text'] = 'Set a new availability:'
        return ctx


class AvailabilityUpdateView(GroupRequiredMixin, UpdateView):
    group_required = ['Teachers']
    model = Availability
    title = 'Update availability'
    template_name = 'reservation/entity_create_update.html'
    form_class = AvailabilityForm

    def get_success_url(self):
        profile = get_object_or_404(Profile, user=self.request.user)
        teacher = get_object_or_404(Teacher, profile=profile)
        return reverse_lazy('reservation:availability-list', kwargs={'teacher_id': teacher.pk})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['text'] = 'Update the availability:'
        return ctx

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        profile = get_object_or_404(Profile, user=self.request.user)
        teacher = get_object_or_404(Teacher, profile=profile)
        kwargs['teacher'] = teacher
        return kwargs


class AvailabilityDeleteView(GroupRequiredMixin, DeleteView):
    group_required = ['Teachers']
    model = Availability
    title = 'Delete availability'
    template_name = 'reservation/availability_delete.html'

    def get_success_url(self):
        profile = get_object_or_404(Profile, user=self.request.user)
        teacher = get_object_or_404(Teacher, profile=profile)
        return reverse_lazy('reservation:availability-list', kwargs={'teacher_id': teacher.pk})

class LessonDetailView(GroupRequiredMixin, DetailView):
    group_required = ['Teachers', 'Students']
    model = Lesson
    title = 'View lesson'
    template_name = 'reservation/lesson_detail.html'


class LessonCreateView(GroupRequiredMixin, CreateView):
    group_required = ['Students']
    model = Lesson
    title = 'Book a lesson'
    template_name = 'reservation/entity_create_update.html'
    form_class = LessonForm

    def get_availability(self):
        return get_object_or_404(Availability, pk=self.kwargs['availability_id'])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        availability = self.get_availability()
        kwargs['date'] = availability.date
        teacher_availabilities = Availability.objects.filter(teacher=availability.teacher, date__gte=make_aware(datetime.now())).order_by('date')
        kwargs['teacher_availabilities'] = [a.date for a in teacher_availabilities]
        kwargs['teacher_subjects'] = availability.teacher.subjects.replace(',', '').split()
        return kwargs

    def form_valid(self, form):
        availability = self.get_availability()
        form.instance.student = self.request.user.profile
        form.instance.teacher = availability.teacher
        self.request.session['teacher_pk'] = availability.teacher.pk
        subject = form.cleaned_data.get('subject')

        # teacher notification
        Notification.objects.create(
            profile=availability.teacher.profile,

reservation/templates/reservation/availability_create.html
{% extends "base.html" %}

{% block title %} {{ view.title }} {% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    {{ form.media }}
{% endblock %}

reservation/templates/reservation/availability_create_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %} {{ view.title }} {% endblock %}

{% block content %}
    <style>
        .full-page-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: flex-start;
            min-height: calc(100vh - 60px);
            text-align: center;
            position: relative;
            padding-top: 40px;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        }
        .container {
            width: 100%;
            max-width: 400px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 8px;
            background-color: #ffffff;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-top: 40px;
        }
        .back-button {
            position: absolute;
            top: 20px;
            left: 20px;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            z-index: 10;
        }
        h2 {
            color: #333333;
            margin-bottom: 20px;
            margin-top: 50px;
        }
    </style>

    <div class="full-page-container">
        <input type="button" value="← Back" onClick="history.go(-1);" class="btn-custom back-button">
        <h2>{{ text }}</h2>
        <div class="container">
            <form method="post">{% csrf_token %}
                {{ form | crispy }}
                <input type="submit" class="btn-custom" value="Save">
            </form>
            {{ form.media }}
        </div>
    </div>
{% endblock %}

reservation/templates/reservation/availability_list.html
{% extends "base.html" %}

{% block title %} {{ title }} {% endblock %}

{% block head %}
<style>
    html, body {
        height: 100%;
        margin: 0;
    }
    .calendar {
        display: flex;
        margin: 30px 0 10px;
        flex-direction: column;
        gap: 10px;
        padding: 0 20px;
    }
    .calendar-week {
        display: flex;
        width: 100%;
        gap: 10px;
        justify-content: space-between;
    }
    .calendar-day {
        border: 1px solid #ddd;
        padding: 10px;
        box-sizing: border-box;
        flex: 1;
        min-width: 120px;
        height: 150px;
        display: flex;
        flex-direction: column;
        justify-content: flex-start;
        background-color: #e3f2fd;
        overflow: hidden;
        position: relative;
    }
    .calendar-day.today {
        background-color: #c9cff9;
    }
    .calendar-day h4 {
        margin: 0;
        text-align: center;
        background: #5d9bde;
        color: #fff;
        padding: 5px;
        border-bottom: 1px solid #ddd;
        font-size: 14px;
        position: sticky;
        top: 0;
        z-index: 1;
    }
    .calendar-day ul {
        list-style: none;
        padding: 0;
        margin: 0;
        text-align: center;
        flex-grow: 1;
        overflow-y: auto;
    }
    .calendar-day li {
        font-size: 14px;
        position: relative;
        cursor: pointer;
        padding: 5px;
    }
    .calendar-day li.availability {
        background-color: #e0f4ac;
    }
    .calendar-day li.lesson {
        background-color: #f4bcac;
    }
    .calendar-day li:hover .action-buttons {
        display: flex;
    }
    .action-buttons {
        display: none;
        position: absolute;
        background: #f1f1f1;
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 5px;
        font-size: 12px;
        z-index: 10;
        white-space: nowrap;
        top: 100%;
        left: 50%;
        transform: translateX(-50%);
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }
    .action-buttons button {
        background: #4CAF50;
        color: #fff;
        border: none;
        padding: 5px 10px;
        margin: 0 5px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 12px;
    }
    .action-buttons button:hover {
        background: #45a049;
    }
    .calendar-header {
        text-align: center;
        margin: 30px 0 10px;
        font-size: 20px;
        font-weight: bold;
    }
    .back-button {
        position: absolute;
        top: 70px;
        left: 20px;
        padding: 10px 20px;
        z-index: 10;
    }
    .centered-button-container {
        display: flex;
        justify-content: center;
        margin-top: 15px;
    }
</style>
{% endblock %}

{% block content %}
    <input type="button" value="← Back" onClick="history.go(-1);" class="back-button btn-custom">
    <div class="calendar-header">Teacher {{ teacher_name }} availabilities:</div>
    <div class="calendar">
        {% for week in calendar_weeks %}
            <div class="calendar-week">
                {% for day in week %}
                    <div class="calendar-day {% if day.date == today %}today{% endif %}">
                        <h4>{{ day.date|date:"D, M j" }}</h4>
                        <ul>
                            {% for event in day.events %}
                                {% if event.type == 'availability' %}
                                    <li class="availability">
                                        {{ event.time }}
                                        <div class="action-buttons">
                                            {% if is_me %}
                                                <form id="availability-form" method="post" action="{% url 'reservation:availability-update' event.id %}">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn-custom">Change</button>
                                                </form>
                                                <form id="delete-form" method="get" action="{% url 'reservation:availability-delete' event.id %}">
                                                    <button type="submit" class="btn-custom">Delete</button>
                                                </form>
                                            {% else %}
                                                <a href="{% url 'reservation:lesson-create' event.id %}" class="btn-custom">Book lesson</a>
                                            {% endif %}
                                        </div>
                                    </li>
                                {% else %}
                                    <li class="lesson">
                                        {{ event.time }} - {{ event.subject }}
                                        <div class="action-buttons">
                                            <form id="lesson-form" method="post" action="{% url 'reservation:lesson-view' event.id %}">
                                                {% csrf_token %}
                                                <button type="submit" class="btn-custom">View lesson</button>
                                            </form>
                                        </div>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>

        <div class="centered-button-container">
            {% if is_me %}
                <form id="availability-form" method="post" action="{% url 'reservation:availability-create' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn-custom">Set new availability</button>
                </form>
            {% else %}
                <h3>Click on an availability to book a lesson</h3>
            {% endif %}
        </div>

    <script>
        document.querySelectorAll('.calendar-day li').forEach(li => {
            li.addEventListener('mouseenter', function(e) {
                const buttons = this.querySelector('.action-buttons');
                if (buttons) {
                    buttons.style.display = 'flex';
                }
            });

            li.addEventListener('mouseleave', function() {
                const buttons = this.querySelector('.action-buttons');
                if (buttons) {
                    buttons.style.display = 'none';
                }
            });
        });
    </script>
{% endblock %}

reservation/templates/reservation/calendar.html
{% extends "base.html" %}

{% block title %} {{ title }} {% endblock %}

{% block head %}
<style>
    html, body {
        height: 100%;
        margin: 0;
    }
    .calendar {
        display: flex;
        margin: 30px 0 10px;
        flex-direction: column;
        gap: 10px;
        padding: 0 20px;
    }
    .calendar-week {
        display: flex;
        width: 100%;
        gap: 10px;
        justify-content: space-between;
    }
    .calendar-day {
        border: 1px solid #ddd;
        padding: 10px;
        box-sizing: border-box;
        flex: 1;
        min-width: 120px;
        height: 150px;
        display: flex;
        flex-direction: column;
        justify-content: flex-start;
        background-color: #e3f2fd;
        overflow: hidden;
        position: relative;
    }
    .calendar-day.today {
        background-color: #c9cff9;
    }
    .calendar-day h4 {
        margin: 0;
        text-align: center;
        background: #5d9bde;
        color: #fff;
        padding: 5px;
        border-bottom: 1px solid #ddd;
        font-size: 14px;
        position: sticky;
        top: 0;
        z-index: 1;
    }
    .calendar-day ul {
        list-style: none;
        padding: 0;
        margin: 0;
        text-align: center;
        flex-grow: 1;
        overflow-y: auto;
    }
    .calendar-day li {
        font-size: 14px;
        position: relative;
        cursor: pointer;
        padding: 5px;
    }
    .calendar-day li.availability {
        background-color: #e0f4ac;
    }
    .calendar-day li.lesson {
        background-color: #f4bcac;
    }
    .calendar-day li:hover .action-buttons {
        display: flex;
    }
    .action-buttons {
        display: none;
        position: absolute;
        background: #f1f1f1;
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 5px;
        font-size: 12px;
        z-index: 10;
        white-space: nowrap;
        top: 100%;
        left: 50%;
        transform: translateX(-50%);
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }
    .action-buttons button {
        background: #4CAF50;
        color: #fff;
        border: none;
        padding: 5px 10px;
        margin: 0 5px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 12px;
    }
    .action-buttons button:hover {
        background: #45a049;
    }
    .action-buttons .change-button {
        margin-right: 2px;
    }
    .action-buttons .delete-button {
        margin-left: 2px;
    }
    .calendar-header {
        text-align: center;
        margin: 30px 0 10px;
        font-size: 20px;
        font-weight: bold;
    }
    .centered-button-container {
        display: flex;
        justify-content: center;
        margin-top: 15px;
    }
    .align-link-profile{
        margin-right: 40px;
    }
    .btn-danger {
        margin-top: 10px;
        background-color: #dc3545;
        padding: 10px 20px;
        font-size: 1em;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        color: white;
    }
    .btn-danger:hover {
        background: #dc3545;
    }
</style>
{% endblock %}

{% block content %}
    <input type="button" value="← Back" onClick="window.location.href='{% if is_me %}{% url 'user_profile:profile' %}{% else %}{% url 'user_profile:view-profile' teacher_profile_id %}{% endif %}';" class="back-button btn-custom">
    <div class="calendar-header">Teacher {{ teacher_name }} availabilities:</div>
    <div class="calendar">
        {% for week in calendar_weeks %}
            <div class="calendar-week">
                {% for day in week %}
                    <div class="calendar-day {% if day.date == today %}today{% endif %}">
                        <h4>{{ day.date|date:"D, M j" }}</h4>
                        <ul>
                            {% for event in day.events %}
                                {% if event.type == 'availability' %}
                                    <li class="availability">
                                        {{ event.time }}
                                        <div class="action-buttons">
                                            {% if event.is_future %}
                                                {% if is_me %}
                                                    <a href="{% url 'reservation:availability-update' event.id %}" class="btn-custom change-button" style="text-decoration: none;">Change</a>
                                                    <a href="{% url 'reservation:availability-delete' event.id %}" class="btn-custom delete-button btn-danger" style="text-decoration: none;">Delete</a>
                                                {% else %}
                                                    <a href="{% url 'reservation:lesson-create' event.id %}" class="btn-custom" style="text-decoration: none;">Book lesson</a>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    </li>
                                {% else %}
                                    <li class="lesson">
                                        {{ event.time }} - {{ event.subject }}
                                        {% if event.is_future %}
                                            <div class="action-buttons">
                                                <a href="{% url 'reservation:lesson-view' event.id %}" class="btn-custom" style="text-decoration: none;">View lesson</a>
                                            </div>
                                        {% endif %}
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>

        <div class="centered-button-container">
            {% if is_me %}
                <a href="{% url 'reservation:availability-create'%}" class="btn-custom" style="text-decoration: none;">Set new availability</a>
            {% else %}
                <h3>Click on an availability to book a lesson</h3>
            {% endif %}
        </div>

    <script>
        document.querySelectorAll('.calendar-day li').forEach(li => {
            li.addEventListener('mouseenter', function(e) {
                const buttons = this.querySelector('.action-buttons');
                if (buttons) {
                    buttons.style.display = 'flex';
                }
            });

            li.addEventListener('mouseleave', function() {
                const buttons = this.querySelector('.action-buttons');
                if (buttons) {
                    buttons.style.display = 'none';
                }
            });
        });
    </script>
{% endblock %}

{% block bar %}
    {% if user.is_authenticated %}
        <a href="{% url 'user_profile:profile' %}" class="link-profile-image align-link-profile">
            <img src="{{ user.profile.picture.url }}" alt="Link-profile">
        </a>
    {% else %}
        <form id="login-form" method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <a href="{% url 'login' %}" class="login align-link-profile">
                Log in
            </a>
        </form>
        {{ form.media }}
    {% endif %}
{% endblock %}