chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'
urlpatterns = [
    path('start-chat/<int:dest_pk>/', start_chat, name='chat-start'),
    path('view/', chat_home, name='chat-home'),
    path('view/<int:pk>/', chat_view, name='chat-view'),
    path('delete/<int:pk>/', chat_delete, name='chat-delete'),
]

findLessons/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$|^/$|^home/$', homepage, name='homepage'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change-password'),
    path('profile/', include('user_profile.urls')),
    path('reservation/', include('reservation.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from .views import *

app_name = 'reservation'

urlpatterns = [
    path('', get_reservation_home, name='reservation_home'),
    path('search/<str:subject>/<str:city>/', get_filtered_list, name='search'),
    path('availability/<int:teacher_id>/', get_calendar, name='availability-list'),
    path('availability/create/', AvailabilityCreateView.as_view(), name='availability-create'),
    path('availability/update/<int:pk>/', AvailabilityUpdateView.as_view(), name='availability-update'),
    path('availability/delete/<int:pk>/', AvailabilityDeleteView.as_view(), name='availability-delete'),
    path('lesson/<int:pk>/', LessonDetailView.as_view(), name='lesson-view'),
    path('lesson/create/<int:availability_id>/', LessonCreateView.as_view(), name='lesson-create'),
    path('lesson/update/<int:pk>/', LessonUpdateView.as_view(), name='lesson-update'),
    path('lesson/delete/<int:pk>/<str:action>/', delete_lesson, name='lesson-delete'),
    path('rating/<int:teacher_id>/', create_update_rating, name='rating-create-update'),
    path('rating/delete/<int:pk>/', RatingDeleteView.as_view(), name='rating-delete'),
]

user_profile/urls.py
from django.urls import path
from .views import *

app_name = 'user_profile'
urlpatterns = [
    path('', profile_home, name='profile'),
    path('view/<int:pk>/', view_profile, name='view-profile'),
    path('set/', ProfileUpdateView.as_view(), name='set-profile'),
    path('set/teacher/', TeacherUpdateView.as_view(), name='set-teacher'),
    path('notification/', get_notifications, name='view-notification'),
    path('notification/delete/<int:pk>/', delete_notification, name='delete-notification'),
    path('request/<int:pk>/', RequestDetailView.as_view(), name='request-detail'),
    path('request/create/', RequestCreateView.as_view(), name='request-create'),
    path('request/delete/<int:pk>/<str:action>/', delete_request, name='request-delete'),
]

user_profile/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.db import models
from PIL import Image
from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    tel_number = models.CharField(max_length=10, blank=True, default='')
    picture = models.ImageField(default='default_profile.jpg', upload_to='profile_imgs')

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.picture.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.picture.path)

    def __str__(self):
        return 'ID: ' + str(self.pk) + ' -> ' + self.first_name + ' ' + self.last_name + ' ' + str(self.email)


class Teacher(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    subjects = models.CharField(max_length=255, default='Insert subjects comma separated')
    city = models.CharField(max_length=30)
    price = models.IntegerField(default=0,validators=[
            MinValueValidator(0, message=_('Value must be greater than or equal to 0'))])
    stars = models.FloatField(default=0, validators=[
            MinValueValidator(0.0, message=_('Value must be greater than or equal to 0.0')),
            MaxValueValidator(5.0, message=_('Value must be less than or equal to 5.0'))])

    def __str__(self):
        return ('ID: ' + str(self.pk) + ' -> ' + self.city + ' ' + self.subjects+ ' ' + str(self.price) + ' ' +
                str(self.stars))


class Notification(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='notifications')
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f'Notification for {self.profile.first_name} {self.profile.last_name}: {self.message}'


class Request(models.Model):
    username = models.CharField(max_length=150)
    encrypted_password = models.CharField(max_length=255)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    identification = models.ImageField(upload_to='ID_imgs')
    timestamp = models.DateTimeField(auto_now_add=True)

    # Encrypt the password using the key from settings
    def set_password(self, raw_password):
        fernet = Fernet(settings.ENCRYPTION_KEY.encode())
        encrypted_password = fernet.encrypt(raw_password.encode())
        self.encrypted_password = encrypted_password.decode()

    # Decrypt the password using the key from settings
    def get_password(self):
        try:
            fernet = Fernet(settings.ENCRYPTION_KEY.encode())
            return fernet.decrypt(self.encrypted_password.encode()).decode()
        except InvalidToken:
            return "Invalid token or corrupted data"

    def __str__(self):
        return 'ID: ' + str(self.pk) + ' -> Request from ' + self.first_name + ' ' + self.last_name + ' ' + str(self.email)

user_profile/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from user_profile.models import Profile, Teacher, Request


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'profile_form'
        self.helper.form_method = 'post'
        self.helper.form_enctype = 'multipart/form-data'
        self.helper.add_input(Submit('submit', 'Submit'))

        if self.instance:
            self.fields['picture'].widget.attrs['value'] = self.instance.picture.url
            self.fields['first_name'].widget.attrs['value'] = self.instance.first_name
            self.fields['last_name'].widget.attrs['value'] = self.instance.last_name
            self.fields['email'].widget.attrs['value'] = self.instance.email
            self.fields['tel_number'].widget.attrs['value'] = self.instance.tel_number

    class Meta:
        model = Profile
        fields = ['picture', 'first_name', 'last_name', 'email', 'tel_number']


class TeacherForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TeacherForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'teacher_form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))

        if self.instance:
            self.fields['city'].widget.attrs['value'] = self.instance.city
            self.fields['subjects'].widget.attrs['value'] = self.instance.subjects
            self.fields['price'].widget.attrs['value'] = self.instance.price

    class Meta:
        model = Teacher
        fields = ['city', 'subjects', 'price']

class RequestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RequestForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'request_form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Send request'))

    class Meta:
        model = Request
        fields = ['first_name', 'last_name', 'email', 'identification']
        labels = {
            'identification': 'Insert a picture of your identification document',
        }

user_profile/views.py
from django.http import Http404, HttpResponseForbidden, HttpResponseBadRequest
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.models import Group
from django.utils.crypto import get_random_string
from django.views.generic import UpdateView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from braces.views import GroupRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail

from reservation.models import Lesson, Rating
from .models import *
from .forms import ProfileForm, TeacherForm, RequestForm

# Create your views here.view

@login_required
def profile_home(request):
    profile = get_object_or_404(Profile, user=request.user)
    ctx = {'title': 'User profile', 'profile': profile, 'is_me': True, 'is_student': False, 'is_admin':False}

    notifications = request.user.profile.notifications.all()
    if notifications.exists():
        news = True
        for n in notifications:
            news = news and n.read
        ctx['news'] = not news
    else:
        ctx['news'] = False

    chat_news = False
    for chat in profile.chats.all():
        chat_news = chat_news or chat.has_new_messages(profile)
    ctx['chat_news'] = chat_news

    if request.user.is_superuser:
        template = 'user_profile/admin_profile.html'
        ctx['requests'] = Request.objects.all()
        ctx['is_admin'] = True
    elif request.user.groups.filter(name='Teachers').exists():
        template = 'user_profile/teacher_profile.html'
        teacher = get_object_or_404(Teacher, profile=profile)
        ctx['teacher'] = teacher
    else:
        template = 'user_profile/student_profile.html'
        ctx['today'] = timezone.now()
        ctx['lessons'] = Lesson.objects.all().filter(student=profile).order_by('date')
        ctx['ratings'] = Rating.objects.filter(student=profile)
        ctx['is_student'] = True

    if request.method == 'POST':
        profile_data = {key: request.POST[key] for key in ('first_name', 'last_name', 'email', 'tel_number', 'picture')
                        if key in request.POST}
        profile_form = ProfileForm(profile_data, request.FILES, instance=profile)

        teacher_form = None
        if 'teacher' in ctx:
            teacher_data = {key: request.POST[key] for key in ('city', 'subjects', 'price') if key in request.POST}
            teacher_form = TeacherForm(teacher_data, instance=ctx['teacher'])

        if profile_form.is_valid() and (teacher_form is None or teacher_form.is_valid()):
            profile_form.save()
            profile.refresh_from_db()
            ctx['profile'] = profile

            if teacher_form:
                teacher_form.save()
                ctx['teacher'].refresh_from_db()

    return render(request, template_name=template, context=ctx)


def view_profile(request, pk):

    profile = get_object_or_404(Profile, pk=pk)
    use_history = True if request.GET.get('source', None) else False
    ctx = {'title': 'View profile', 'profile': profile, 'is_me': False, 'is_admin': False, 'use_history': use_history}

    if profile.user.is_superuser:
        raise Http404
    elif profile.user.groups.filter(name='Teachers').exists():
        template = 'user_profile/teacher_profile.html'
        teacher = get_object_or_404(Teacher, profile=profile)
        ctx['teacher'] = teacher
    else:
        template = 'user_profile/view_student_profile.html'
        ctx['today'] = timezone.now()

        if request.user.groups.filter(name='Teachers').exists():
            ctx['lessons'] = Lesson.objects.all().filter(student=profile, teacher=request.user.profile.teacher).order_by('date')
        else:
            ctx['lessons'] = []

    return render(request, template_name=template, context=ctx)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    title = 'Update Profile'
    form_class = ProfileForm
    template_name = 'user_profile/profile_teacher_request_update.html'
    success_url = reverse_lazy('user_profile:profile')

    def get_object(self, queryset=None):
        return get_object_or_404(Profile, user=self.request.user)


class TeacherUpdateView(GroupRequiredMixin, UpdateView):
    group_required = ['Teachers']
    model = Teacher
    title = 'Update Teacher'
    form_class = TeacherForm
    template_name = 'user_profile/profile_teacher_request_update.html'
    success_url = reverse_lazy('user_profile:profile')

    def get_object(self, queryset=None):
        profile = get_object_or_404(Profile, user=self.request.user)
        return get_object_or_404(Teacher, profile=profile)


def get_notifications(request):
    notifications = request.user.profile.notifications.all().order_by('-timestamp')
    for n in notifications:
        n.read = True
        n.save()

    ctx = {'title': 'View notifications', 'news': notifications}

    return render(request, template_name='user_profile/news_list.html', context=ctx)


@login_required
def delete_notification(request, pk):
    Notification.objects.get(pk=pk).delete()
    return redirect('user_profile:view-notification')


class RequestCreateView(CreateView):
    model = Request
    form_class = RequestForm
    title = 'Registration request'
    template_name = 'user_profile/profile_teacher_request_update.html'
    success_url = reverse_lazy('homepage')

    def get(self, request, *args, **kwargs):
        if 'teacher_username' not in request.session or 'teacher_password' not in request.session:
            return redirect('login')

        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        username = self.request.session.get('teacher_username')
        password = self.request.session.get('teacher_password')

        if not username or not password:
            return redirect('login')

        request_instance = form.save(commit=False)
        request_instance.username = username
        request_instance.set_password(password)
        request_instance.save()

        self.request.session.pop('teacher_username', None)
        self.request.session.pop('teacher_password', None)

        # create a temporary user to keep the username
        user = User(username=username)
        user.set_password(get_random_string(length=12))
        user.save()

        return super().form_valid(form)


class RequestDetailView(UserPassesTestMixin, DetailView):
    model = Request
    title = 'View request'
    template_name = 'user_profile/request_detail.html'

    def test_func(self):
        return self.request.user.is_superuser

@login_required
def delete_request(request, pk, action):

    if not request.user.is_superuser:
        return HttpResponseForbidden("Superuser permission needed")
    if action not in ['accept', 'reject']:
        return HttpResponseBadRequest("Invalid action parameter")

    teacher_request = get_object_or_404(Request, pk=pk)

    subject = 'FindLessons: outcome of the registration request'
    message = (f'Hello {teacher_request.first_name}, \nwe are sorry but your registration request was rejected.'
               f'\n\nBest regards, \nFindLessons team.')
    from_email = 'findlessons2024@gmail.com'
    recipient_list = [teacher_request.email]

    user = User.objects.get(username=teacher_request.username)

    if action == 'accept':
        user.set_password(teacher_request.get_password())
        user.save()

        teachers_group = Group.objects.get(name='Teachers')
        user.groups.add(teachers_group)

        user.profile.first_name = teacher_request.first_name
        user.profile.last_name = teacher_request.last_name
        user.profile.email = teacher_request.email
        user.profile.save()

        message = (f'Hello {teacher_request.first_name}, \nWe are pleased to announce that your registration request '
               f'has been accepted.\nYou can now log in to your account with the following username: '
                   f'{teacher_request.username}\n\nBest regards, \nFindLessons team.')
    else:
        user.delete()

    # Delete the ID for privacy reasons
    if teacher_request.identification:
        teacher_request.identification.delete(save=False)

    teacher_request.delete()

    send_mail(subject, message, from_email, recipient_list)

    return redirect('user_profile:profile')

user_profile/templates/user_profile/admin_profile.html
{% extends 'user_profile/profile.html' %}

{% block head %}
    {{ block.super }}

    <style>
        .info-container {
            flex: 1;
            display: flex;
            flex-direction: column;
            overflow-y: auto;
            box-sizing: border-box;
            padding: 20px;
            width: 100%;
            position: relative;
        }
        .request-box {
            display: flex;
            align-items: flex-start;
            gap: 20px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 10px;
            opacity: 0;
            transition: opacity 0.3s, display 0s 0.3s;
            position: relative;
            cursor: pointer;
        }
        .request-box.visible {
            opacity: 1;
            display: flex;
            transition: opacity 0.3s;
        }
        .request-content {
            display: flex;
            flex-direction: column;
            width: 100%;
            margin-bottom: 20px;
        }
        .request-timestamp {
            font-size: 0.9em;
            color: #666666;
            margin-bottom: 5px;
        }
        .request-info {
            font-size: 1.1em;
            color: #333333;
        }
        .request-id {
            position: absolute;
            bottom: 20px;
            right: 20px;
        }
    </style>

{% endblock %}

{% block info %}
    <div class="list">
        <h2 id="header-title">Requests:</h2>
        <div class="info-container" id="requests-container">
            {% for request in requests %}
                <div class="request-box visible" tabindex="0">
                    <div class="request-content">
                        <p class="request-timestamp">{{ request.timestamp|date:"F j, Y, g:i a" }}</p>
                        <p class="request-info">
                            <strong>Name: </strong>{{ request.first_name }} {{ request.last_name }} <br>
                            <strong>Email: </strong>{{ request.email }} <br>
                        </p>
                    </div>
                    <div class="request-id">
                        <a href="{% url 'user_profile:request-detail' request.pk %}" class="btn-custom" style="text-decoration: none;">View ID</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

user_profile/templates/user_profile/student_profile.html
{% extends 'user_profile/profile.html' %}
{% load static %}

{% block head %}
    {{ block.super }}
    <style>
        .info-container {
            flex: 1;
            display: flex;
            flex-direction: column;
            overflow-y: auto;
            box-sizing: border-box;
            padding: 20px;
            width: 100%;
            position: relative;
        }
        .lesson-box, .rating-box {
            display: flex;
            align-items: center;
            gap: 20px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 10px;
            opacity: 0;
            transition: opacity 0.3s, display 0s 0.3s;
            position: relative;
            cursor: pointer;
        }
        .lesson-box.visible, .rating-box.visible {
            opacity: 1;
            display: flex;
            transition: opacity 0.3s;
        }
        .lesson-box.light-gray {
            background-color: #d3d3d3;
        }
        .lesson-box.light-blue {
            background-color: #add8e6;
        }
        .rating-box.light-yellow {
            background-color: #f3f6e1;
        }
        .teacher-picture {
            width: 90px;
            height: 90px;
            border-radius: 50%;
            object-fit: cover;
            margin: 20px;
        }
        .lesson-info {
            display: flex;
            flex-direction: column;
        }
        .action-buttons {
            display: none;
            position: fixed;
            background: #f1f1f1;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 5px;
            font-size: 12px;
            z-index: 10;
            white-space: nowrap;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }
        .action-buttons button, .action-buttons a {
            border: none;
            padding: 5px 10px;
            margin: 0 5px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 12px;
        }
        .delete-button {
            background-color: #dc3545;
            color: white;
        }
        .delete-button:hover {
            background-color: #dc3545;
        }
        .modal {
            display: none;
            position: fixed;
            z-index: 1000;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0,0,0,0.4);
            justify-content: center;
            align-items: center;
        }
        .modal-content {
            background-color: #fefefe;
            margin: 15% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 80%;
            max-width: 500px;
            border-radius: 8px;
            text-align: center;
        }
        .modal-button-container {
            display: flex;
            justify-content: space-around;
            margin-top: 20px;
        }
        .modal-button {
            padding: 10px 20px;
            font-size: 1em;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin: 0 5px;
        }
        .modal-button.delete {
            background-color: #dc3545;
            color: white;
        }
        .modal-button.cancel {
            background-color: #6c757d;
            color: white;
        }
        .modal-button:hover {
            opacity: 0.8;
        }

        .star-rating {
            display: inline-block;
            font-size: 2em;
            color: #ccc;
            margin-top: 10px;
        }

        .star {
            position: relative;
            display: inline-block;
            width: 1em;
            overflow: hidden;
        }

        .star.full {
            color: #f39c12;
        }

        .star.half::before,
        .star.quarter::before,
        .star.three-quarters::before {
            content: '\2605';
            position: absolute;
            top: 0;
            left: 0;
            height: 100%;
            overflow: hidden;
            color: #f39c12;
        }

        .star.quarter::before {
            width: 35%;              /* Set to 35% instead of 25% for a better visualization*/
        }

        .star.half::before {
            width: 45%;              /* Set to 45% instead of 50% for a better visualization*/
        }

        .star.three-quarters::before {
            width: 55%;               /* Set to 55% instead of 75% for a better visualization*/
        }

        .star.empty {
            color: #ccc;
        }

    </style>
{% endblock %}

{% block info %}
  <div class="list">
        <h2 id="header-title">Your lessons:</h2>
        <div class="info-container" id="lessons-container">
            {% for lesson in lessons %}
                <div class="lesson-box {% if lesson.date < today %}light-gray{% else %}light-blue{% endif %} visible" tabindex="0">
                    <img class="teacher-picture" src="{{ lesson.teacher.profile.picture.url }}" alt="Teacher Picture">
                    <div class="lesson-info">
                        <p><strong>{{ lesson.subject }}</strong></p>
                        <p>{{ lesson.teacher.profile.first_name }} {{ lesson.teacher.profile.last_name }}</p>
                        <p>{{ lesson.date |date:"H:i, d F"}}</p>
                    </div>
                    <div class="action-buttons">
                        <a href="{% url 'user_profile:view-profile' lesson.teacher.profile.id %}" class="btn-custom" style="text-decoration: none;">View teacher</a>
                        {% if lesson.date < today %}
                            <a href="{% url 'reservation:rating-create-update' lesson.teacher.id %}" class="btn-custom" style="text-decoration: none;">Rate</a>
                        {% endif %}
                        <button class="btn-custom delete-button" data-lesson-id="{{ lesson.id }}">Delete</button>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="info-container" id="ratings-container" style="display:none;">
            {% for rating in ratings %}
                <div class="rating-box light-yellow visible" tabindex="0" data-rating="{{ rating.stars }}" data-rating-id="{{ rating.id }}">
                    <img class="teacher-picture" src="{{ rating.teacher.profile.picture.url }}" alt="Teacher Picture">
                    <div class="lesson-info">
                        <p><strong>{{ rating.teacher.profile.first_name }} {{ rating.teacher.profile.last_name }}</strong></p>
                        <div class="star-rating">
                            <span class="star empty">&#9733;</span>
                            <span class="star empty">&#9733;</span>
                            <span class="star empty">&#9733;</span>
                            <span class="star empty">&#9733;</span>
                            <span class="star empty">&#9733;</span>
                        </div>
                    </div>
                    <div class="action-buttons">
                        <a href="{% url 'user_profile:view-profile' rating.teacher.profile.id %}" class="btn-custom" style="text-decoration: none;">Show teacher</a>
                        <a href="{% url 'reservation:rating-create-update' rating.teacher.id %}" class="btn-custom" style="text-decoration: none;">Change rate</a>
                        <button class="btn-custom delete-button" data-rating-id="{{ rating.id }}">Delete</button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div id="confirmationModal" class="modal">
        <div class="modal-content">
            <h5 id="modal-message">Are you sure you want to delete this item?</h5>
            <div class="modal-button-container">
                <form id="deleteForm" method="post">
                    {% csrf_token %}
                    <button type="submit" class="modal-button delete">Delete</button>
                </form>
                <button class="modal-button cancel" id="closeModalButton">Cancel</button>
            </div>
        </div>
    </div>

    <script src="{% static 'js/star_rating.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const ratingContainers = document.querySelectorAll('.rating-box');
            ratingContainers.forEach(container => {
                const rating = parseFloat(container.dataset.rating);
                const starRatingElement = container.querySelector('.star-rating');
                viewStars(starRatingElement, rating);
            });
        });

        document.querySelectorAll('.lesson-box').forEach(li => {
            li.addEventListener('mouseenter', function(e) {
                const buttons = this.querySelector('.action-buttons');
                if (buttons) {
                    const rect = li.getBoundingClientRect();
                    buttons.style.top = `${rect.top + rect.height / 4}px`;
                    buttons.style.left = `${rect.right-25}px`;
                    buttons.style.display = 'flex';
                }
            });

            li.addEventListener('mouseleave', function() {
                const buttons = this.querySelector('.action-buttons');
                if (buttons) {
                    buttons.style.display = 'none';
                }
            });
        });

        document.querySelectorAll('.rating-box').forEach(li => {
            li.addEventListener('mouseenter', function(e) {
                const buttons = this.querySelector('.action-buttons');
                if (buttons) {
                    const rect = li.getBoundingClientRect();
                    buttons.style.top = `${rect.top + rect.height / 4}px`;
                    buttons.style.left = `${rect.right-25}px`;
                    buttons.style.display = 'flex';
                }
            });

            li.addEventListener('mouseleave', function() {
                const buttons = this.querySelector('.action-buttons');
                if (buttons) {
                    buttons.style.display = 'none';
                }
            });
        });

        const confirmationModal = document.getElementById('confirmationModal');
        const closeModalButton = document.getElementById('closeModalButton');
        const deleteForm = document.getElementById('deleteForm');

        document.querySelectorAll('.delete-button').forEach(button => {
            button.addEventListener('click', function() {
                const itemId = this.getAttribute('data-lesson-id') || this.getAttribute('data-rating-id');
                const isRating = this.hasAttribute('data-rating-id');
                const actionUrl = isRating
                    ? "{% url 'reservation:rating-delete' 0 %}".replace('/0/', `/${itemId}/`)
                    : "{% url 'reservation:lesson-delete' 0 'action' %}".replace('/0/', `/${itemId}/`).replace('/action/', `/reset/`);

                deleteForm.setAttribute('action', actionUrl);
                document.getElementById('modal-message').textContent = `Are you sure you want to delete this ${isRating ? 'rating' : 'lesson'}?`;
                confirmationModal.style.display = 'flex';
            });
        });

        closeModalButton.addEventListener('click', function() {
            confirmationModal.style.display = 'none';
        });

        window.addEventListener('click', function(event) {
            if (event.target === confirmationModal) {
                confirmationModal.style.display = 'none';
            }
        });
    </script>
{% endblock %}