chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'
urlpatterns = [
    path('start-chat/<int:dest_pk>/', start_chat, name='chat-start'),
    path('view/', chat_home, name='chat-home'),
    path('view/<int:pk>/', chat_view, name='chat-view'),
    path('delete/<int:pk>/', chat_delete, name='chat-delete'),
]

findLessons/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$|^/$|^home/$', homepage, name='homepage'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change-password'),
    path('profile/', include('user_profile.urls')),
    path('reservation/', include('reservation.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from .views import *

app_name = 'user_profile'
urlpatterns = [
    path('', profile_home, name='profile'),
    path('view/<int:pk>/', view_profile, name='view-profile'),
    path('set/', ProfileUpdateView.as_view(), name='set-profile'),
    path('set/teacher/', TeacherUpdateView.as_view(), name='set-teacher'),
    path('notification/', get_notifications, name='view-notification'),
    path('notification/delete/<int:pk>/', delete_notification, name='delete-notification'),
    path('request/<int:pk>/', RequestDetailView.as_view(), name='request-detail'),
    path('request/create/', RequestCreateView.as_view(), name='request-create'),
    path('request/delete/<int:pk>/<str:action>/', delete_request, name='request-delete'),
]

chat/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from user_profile.models import Profile

# Create your models here.


class Chat(models.Model):
    participants = models.ManyToManyField(Profile, related_name='chats')

    def chat_name(self):
        return f'chat_{self.pk}'

    def get_other_participant(self, profile):
        if profile is None or not self.participants.filter(pk=profile.pk).exists():
            return None

        try:
            other_participant = self.participants.exclude(pk=profile.pk).first()
            if other_participant:
                return other_participant
            else:
                return None
        except ObjectDoesNotExist:
            return None

    def has_new_messages(self, profile):
        sender = self.get_other_participant(profile)
        return self.messages.filter(sender=sender, read=False).exists()

    def read_messages(self, profile):
        sender = self.get_other_participant(profile)
        for msg in self.messages.filter(sender=sender, read=False):
            msg.read = True
            msg.save()

    def __str__(self):
        return 'Chat between ' + ','.join([profile.user.username for profile in self.participants.all()])

class Message(models.Model):
    chat = models.ForeignKey(Chat, related_name='messages', on_delete=models.CASCADE)
    sender = models.ForeignKey(Profile, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    class Meta:
        ordering = ('timestamp',)

    def __str__(self):
        return f"{self.sender.user.username}: {self.content[:20]}"

class Visibility(models.Model):
    chat = models.ForeignKey(Chat, related_name='visibility', on_delete=models.CASCADE)
    participant = models.ForeignKey(Profile, related_name='visibility', on_delete=models.CASCADE)
    visible = models.BooleanField(default=True)

chat/views.py
from django.dispatch import receiver
from django.http import HttpResponseBadRequest, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.decorators import login_required
from .models import Chat, Visibility
from user_profile.models import Profile

# Create your views here.

def get_chats_dicts(profile):
    chats = []
    for chat in profile.chats.all():
        new_msg = chat.has_new_messages(profile)

        if chat.visibility.get(participant=profile).visible or new_msg:
            other_participant = chat.get_other_participant(profile)
            if other_participant:
                chats.append(
                    {'id': chat.pk,
                    'other_participant': other_participant,
                    'new_messages': new_msg,}
                )
    return chats

@login_required
def start_chat(request, dest_pk):
    sender = request.user.profile
    receiver = get_object_or_404(Profile, pk=dest_pk)

    if sender == receiver:
        return HttpResponseBadRequest('You cannot chat with yourself' )

    chat = Chat.objects.filter(participants=sender).filter(participants=receiver).distinct().first()

    if not chat:
        chat = Chat.objects.create()
        chat.participants.add(sender, receiver)
        chat.save()
    else:
        chat_visibility  = sender.visibility.filter(chat=chat).first()
        chat_visibility.visible = True
        chat_visibility.save()

    return redirect('chat:chat-view', pk=chat.pk)

@login_required
def chat_view(request, pk):
    current_chat = get_object_or_404(Chat, pk=pk)
    chat_receiver = current_chat.get_other_participant(request.user.profile)

    if request.user.profile not in current_chat.participants.all():
        return HttpResponseForbidden('You can only access to your chat')

    # Prevent accessing "deleted" chat via url and chats without a receiver
    if not current_chat.visibility.get(participant=request.user.profile).visible or chat_receiver is None:
        return redirect('chat:chat-home')

    current_chat.read_messages(request.user.profile)

    ctx = {
        'receiver': chat_receiver,
        'messages': current_chat.messages.all(),
        'chat_name': current_chat.chat_name(),
        'chats': get_chats_dicts(request.user.profile),
        'current_chat_id': current_chat.pk,
    }

    return render(request, 'chat/chat.html', ctx)

@login_required
def chat_home(request):
    ctx = {
        'chats': get_chats_dicts(request.user.profile),
        'chat_name': 'None',
        'messages' : []
    }
    return render(request, 'chat/chat.html', ctx)

@login_required
def chat_delete(request, pk):
    chat = get_object_or_404(Chat, pk=pk)

    if request.user.profile not in chat.participants.all():
        return HttpResponseForbidden('You can only delete your chat')

    delete = True
    for v in chat.visibility.all():
        if v.participant == request.user.profile:
            v.visible = False
            v.save()

        delete = delete and not v.visible

    # Delete the chat only if it is not visible for all of its participants
    if delete:
        chat.delete()

    return redirect('chat:chat-home')

chat/templates/chat/chat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Chat{% endblock %}

{% block head %}
   <style>
        html, body {
            height: 100%;
            margin: 0;
            overflow: hidden;
        }

        .align-link-profile {
            margin-right: 40px;
        }

        .chat-container {
            display: flex;
            height: 100vh;
            overflow: hidden;
        }

        .chat-list {
            width: 25%;
            border-right: 1px solid #ddd;
            padding: 10px;
            box-sizing: border-box;
            overflow-y: auto;
            position: relative;
            height: calc(100vh - 60px);
            max-height: 100%;
        }


        .chat-list h2 {
            position: relative;
            background-color: #fff;
            margin-bottom: 20px;
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            justify-content: space-between;
            text-decoration: none;
            color: black;
        }

        .chat-list h2 img {
            width: 30px;
            height: 30px;
            cursor: pointer;
            position: absolute;
            right: 20px;
            top: 50%;
            transform: translateY(-50%);
        }

        .chat-item {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            justify-content: space-between;
            text-decoration: none;
            background-color: white;
            color: black;
        }
        .chat-item div {
            flex: 1;
            text-align: center;
        }

        .chat-item-img {
            border-radius: 50%;
            width: 40px;
            height: 40px;
            margin-right: 10px;
        }

        .receiver-info {
            display: flex;
            align-items: center;
            border: 1px solid #ddd;
            padding: 10px;
            background-color: #f9f9f9;
            margin-bottom: 10px;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .receiver-info img {
            border-radius: 50%;
            width: 50px;
            height: 50px;
            margin-right: 10px;
        }

        .receiver-info div {
            flex: 1;
        }

        .receiver-info .delete-img {
            width: 30px;
            height: 30px;
            cursor: pointer;
        }
        .chat-messages {
            width: 75%;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            flex: 1;
            overflow: hidden;
            margin-right: 0;
            padding: 10px 10px 70px;
            background-color: #dee1f8;
            overflow-y: auto;
        }

        #chat-log {
            flex: 1;
            overflow-y: auto;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
            max-height: calc(100vh - 160px);
            margin-bottom:60px;
        }


        .message-box {
            max-width: 60%;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 10px;
            word-wrap: break-word;
            color: white;
            text-align: left;
        }

        .message-box.sent {
            background-color: lightseagreen;
            margin-left: auto;
        }

        .message-box.received {
            background-color: lightslategray;
            margin-right: auto;
        }

        .message-input-container {
            position: fixed;
            bottom: 0;
            left: 25%;
            width: 75%;
            display: flex;
            align-items: center;
            padding: 10px;
            box-sizing: border-box;
            background-color: #fff;
            border-top: 1px solid #ddd;
        }
        .message-input-container button{
            font-size: 1em;
            color: #fff;
            background-color: #4CAF50;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        #chat-message-input {
            flex: 1;
            height: 50px;
            margin-right: 10px;
            resize: none;
            background-color: #fff;
            outline: none;
        }

        #chat-message-submit {
            width: 60px;
            height: 50px;
        }

        .bell-img {
            width: 30px;
            height: 30px;
            margin-right: 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="chat-container">
        <div class="chat-list">
            <h2>
                Chats
                <img src="{% static 'imgs/refresh.png' %}" onclick="location.reload()" alt="Refresh">
            </h2>
            {% for chat in chats %}
                <div class="chat-item" onclick="location.href='{% url 'chat:chat-start' chat.other_participant.id %}'">
                   <img src="{{ chat.other_participant.picture.url }}" class="chat-item-img" alt="Profile Picture">
                    <div>
                        {% if chat.other_participant.first_name and chat.other_participant.last_name %}
                            {{ chat.other_participant.first_name }} {{ chat.other_participant.last_name }}
                        {% else %}
                            {{ chat.other_participant.user.username }}
                        {% endif %}
                    </div>
                    {% if chat.new_messages %}
                        <img src="{% static 'imgs/bell.png' %}" class="bell-img" alt="New message">
                    {% endif %}
                </div>
            {% empty %}
                <p>No chats available</p>
            {% endfor %}
        </div>

        <div class="chat-messages">
            {% if receiver %}
                <div class="receiver-info">
                    <a href="{% url 'user_profile:view-profile' receiver.id %}?source=chat">
                        <img src="{{ receiver.picture.url }}" alt="Receiver Picture">
                    </a>
                    <div>
                        {% if receiver.first_name and receiver.last_name %}
                            <strong>{{ receiver.first_name }} {{ receiver.last_name }}</strong>
                        {% else %}
                            {{ receiver.user.username }}
                        {% endif %}
                    </div>
                    <a href="{% url 'chat:chat-delete' current_chat_id %}">
                        <img src="{% static 'imgs/delete.png' %}" class="delete-img" alt="Delete">
                    </a>
                </div>
            {% endif %}
            <div id="chat-log">
                {% for message in messages %}
                    <div class="message-box {% if message.sender == request.user.profile %}sent{% else %}received{% endif %}">
                        {{ message.content }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% if receiver %}
        <div class="message-input-container">
            <label for="chat-message-input"></label><textarea id="chat-message-input" type="text"></textarea>
            <button id="chat-message-submit">Send</button>
        </div>
    {% endif %}

    <script>
        const chatName = "{{ chat_name }}";
        const username = "{{ request.user.username }}";
        let chatSocket;

        function setupWebSocket() {
            if (chatName !== "None") {
                chatSocket = new WebSocket(
                    'ws://' + window.location.host + '/ws/chat/' + chatName + '/'
                );

                chatSocket.onmessage = function (e) {
                    const data = JSON.parse(e.data);
                    const messageClass = data.username === username ? 'sent' : 'received';
                    document.querySelector('#chat-log').innerHTML +=
                        '<div class="message-box ' + messageClass + '">' + data.message + '</div>';
                    scrollToBottom();  // Scroll to the bottom after a new message

                    if (data.username !== username) {
                        chatSocket.send(JSON.stringify({
                            'mark_read': true,
                            'message_id': data.message_id
                        }));
                    }
                };

                chatSocket.onclose = function (e) {
                    console.error('Chat socket closed unexpectedly');
                };

                const messageInputDom = document.querySelector('#chat-message-input');
                const sendButton = document.querySelector('#chat-message-submit');

                function toggleSendButton() {
                    sendButton.disabled = messageInputDom.value.trim() === '';
                }

                messageInputDom.addEventListener('input', toggleSendButton);
                messageInputDom.addEventListener('keyup', function (e) {
                    if (e.keyCode === 13 && !sendButton.disabled) {  // enter, return
                        sendButton.click();
                    }
                });

                sendButton.addEventListener('click', function (e) {
                    const message = messageInputDom.value;
                    chatSocket.send(JSON.stringify({
                        'message': message,
                        'username': username
                    }));
                    messageInputDom.value = '';
                    toggleSendButton(); // Disable button after sending
                });

                // Initialize button state
                toggleSendButton();

                // Scroll to bottom on initial load
                scrollToBottom();
            }
        }

        function closeWebSocket() {
            if (chatSocket) {
                chatSocket.close();
            }
        }

        // Function to scroll chat log to the bottom
        function scrollToBottom() {
            const chatLog = document.querySelector('#chat-log');
            chatLog.scrollTop = chatLog.scrollHeight;
        }

        // Setup WebSocket connection
        setupWebSocket();
        scrollToBottom();

        // Ensure WebSocket is closed before the page unloads
        window.addEventListener('beforeunload', function () {
            closeWebSocket();
        });

    </script>

{% endblock %}

{% block bar %}
    <a href="{% url 'user_profile:profile' %}" class="link-profile-image align-link-profile">
        <img src="{{ user.profile.picture.url }}" alt="Link-profile">
    </a>
{% endblock %}